### ISSUE TITLE
I'm confused: port 80 or 8080 ?

### ISSUE THREAD

**Issue by borgogelli** [robmorgan/sample-docker-app#17]
What is not clear to me is on which tcp port does the application respond.

On _docker-compose.yml_ I read
```
...
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
```
while on _Dockerfile_ I read
```
...
EXPOSE 80
```

**Comment by robmorgan** [comment]
Hi @borgogelli, I agree this is a bit confusing. I've changed the app to now always run on port `8080`. See https://github.com/robmorgan/sample-node-app/releases/tag/v0.3.0.

Just a heads up, this might break the [example Terraform repo](https://github.com/robmorgan/terraform-cloudrun-example) as Cloud Run might be expecting the app to run on a different port. I haven't had a chance to test this yet.

**Comment by borgogelli** [comment]
Thank you and regards from Italy
